# Generated by Django 4.1.13 on 2023-11-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='uploads/'),
        ),
    ]
