# Generated by Django 4.1.13 on 2023-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
