# Generated by Django 4.1.13 on 2023-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_quantity', '0002_roomquantity_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomquantity',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
